### ISSUE TITLE
Compilation fails during 'make'

### ISSUE THREAD

**Issue by larmeh** [openzfsonosx/spl#8]
During compilation, I get the following error:

llvm-gcc -DHAVE_CONFIG_H -include ../../spl_config.h  -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing  -Wall -nostdinc -mkernel -fno-builtin-printf -D_KERNEL -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -I../../include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Kernel.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Kernel.framework/PrivateHeaders  -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing   -MT spl-spl-osx.o -MD -MP -MF .deps/spl-spl-osx.Tpo -c -o spl-spl-osx.o `test -f 'spl-osx.c' || echo './'`spl-osx.c
spl-osx.c:318:27: warning: implicit declaration of function 'stac' is invalid in C99 [-Wimplicit-function-declaration]
        if (spl_cpufeature_smap) stac();
                                 ^
spl-osx.c:328:27: warning: implicit declaration of function 'clac' is invalid in C99 [-Wimplicit-function-declaration]
        if (spl_cpufeature_smap) clac();
                                 ^
spl-osx.c:382:18: error: use of undeclared identifier 'CR4_SMAP'
        if (get_cr4() & CR4_SMAP)
                        ^
2 warnings and 1 error generated.
make[4]: *** [spl-spl-osx.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Any ideas as to what it is I am missing?

**Comment by brendonhumphrey** [comment]
Your Xcode is too old.

Brendon

**Comment by larmeh** [comment]
That's weird. I updated it from 6.2 to 6.4 via App Store. After the installation, the button on App Store's XCode page read "Open" i.e. the installation of 6.4 should have been finished. Upon opening the application though, XCode's about dialog read version 6.2. I had to uninstall 6.2, reboot and reinstall 6.4 from the App Store again...
